"""add ai quiz tables

Revision ID: 7f01279d93ed
Revises: ef6bc3a6c4d9
Create Date: 2026-03-27 14:25:42.720247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f01279d93ed'
down_revision: Union[str, Sequence[str], None] = 'ef6bc3a6c4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_quiz_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generated_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_quiz_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_quiz_sessions'))
    )
    op.create_index(op.f('ix_ai_quiz_sessions_id'), 'ai_quiz_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_quiz_sessions_user_id'), 'ai_quiz_sessions', ['user_id'], unique=False)
    op.create_table('ai_quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_quiz_sessions.id'], name=op.f('fk_ai_quiz_answers_session_id_ai_quiz_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_quiz_answers'))
    )
    op.create_index(op.f('ix_ai_quiz_answers_id'), 'ai_quiz_answers', ['id'], unique=False)
    op.create_index(op.f('ix_ai_quiz_answers_session_id'), 'ai_quiz_answers', ['session_id'], unique=False)
    op.create_table('ai_quiz_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('severity_level', sa.String(length=50), nullable=False),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('practice', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_quiz_sessions.id'], name=op.f('fk_ai_quiz_results_session_id_ai_quiz_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_quiz_results')),
    sa.UniqueConstraint('session_id', name='uq_ai_quiz_results_session_id')
    )
    op.create_index(op.f('ix_ai_quiz_results_id'), 'ai_quiz_results', ['id'], unique=False)
    op.create_index(op.f('ix_ai_quiz_results_session_id'), 'ai_quiz_results', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_quiz_results_session_id'), table_name='ai_quiz_results')
    op.drop_index(op.f('ix_ai_quiz_results_id'), table_name='ai_quiz_results')
    op.drop_table('ai_quiz_results')
    op.drop_index(op.f('ix_ai_quiz_answers_session_id'), table_name='ai_quiz_answers')
    op.drop_index(op.f('ix_ai_quiz_answers_id'), table_name='ai_quiz_answers')
    op.drop_table('ai_quiz_answers')
    op.drop_index(op.f('ix_ai_quiz_sessions_user_id'), table_name='ai_quiz_sessions')
    op.drop_index(op.f('ix_ai_quiz_sessions_id'), table_name='ai_quiz_sessions')
    op.drop_table('ai_quiz_sessions')
    # ### end Alembic commands ###
