"""add journal analyses table

Revision ID: 91e60de93911
Revises: c5a087b216b5
Create Date: 2026-03-21 16:42:36.781632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e60de93911'
down_revision: Union[str, Sequence[str], None] = 'c5a087b216b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=50), nullable=False),
    sa.Column('emotion_label', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_journal_analyses_journal_entry_id_journal_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_analyses')),
    sa.UniqueConstraint('journal_entry_id', name='uq_journal_analyses_journal_entry_id')
    )
    op.create_index(op.f('ix_journal_analyses_id'), 'journal_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_journal_analyses_journal_entry_id'), 'journal_analyses', ['journal_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_analyses_journal_entry_id'), table_name='journal_analyses')
    op.drop_index(op.f('ix_journal_analyses_id'), table_name='journal_analyses')
    op.drop_table('journal_analyses')
    # ### end Alembic commands ###
